// function sum(n) {
// 	let ans = 0;
// 	for (let i = 1; i <= n; i++) {
// 		ans = ans + i
// 	}
// 	return ans;
// }

// const ans1 = sum(100);
// console.log(ans1);
// const ans2 = sum(1000);
// console.log(ans2);
// const ans3 = sum(10000);
// console.log(ans3);

// function papa(){
// 	console.log("Mai hu is duniya ka sabse bada papa");
// }
// let myTimeout = setTimeout(papa,5000);
// clearTimeout(myTimeout);
// console.log(myTimeout);
// console.log("Me chala gaya");

// for(var i=0; i<=5; i++) {
// 	setTimeout(() => {
// 	  console.log(i);
// 	}, 1000);
//   }

// // Helper function that returns a promise which resolves after a specified time
// function wait(ms, i) {
// 	return new Promise(function(resolve) {
// 	  setTimeout(function() {
// 		console.log(i); // Log the value of i after the timeout
// 		resolve();
// 	  }, ms);
// 	});
//   }
  
//   // Async function to loop through and log values with delay
//   async function logValues() {
// 	for (var i = 0; i <= 5; i++) {
// 	  await wait(1000, i); // Wait for 1 second and then log the value of i
// 	}
//   }
  
//   // Call the function
//   logValues();

// const map =new Map();
// map.set('name','Rishi');
// map.set('age',21);
// console.log(map.get('name'));

